sonar.projectKey=mlops
sonar.projectName=mlops
sonar.projectVersion=1.0

sonar.sources=src,api
sonar.tests=tests

sonar.python.version=3.12

sonar.sourceEncoding=UTF-8

sonar.exclusions=venv/**,models/**,artifacts/**,notebooks/**